#6_1 task
---
- hosts: server1
  gather_facts: no
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www/html
    app_root: /home/hunna/ansible-nginx-demo/html_demo_site-main
  roles:
    - users
    - http
